# Generated by Django 5.2.8 on 2025-12-06 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
