"""add reposts

Revision ID: 79ee2db95173
Revises: 91547fc476f7
Create Date: 2026-08-29 19:04:05.963188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79ee2db95173'
down_revision: Union[str, Sequence[str], None] = '91547fc476f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reposts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tweet_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tweet_id'], ['tweets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tweet_id', name='unique_user_tweet_repost')
    )
    op.create_index(op.f('ix_reposts_id'), 'reposts', ['id'], unique=False)
    op.create_index(op.f('ix_reposts_tweet_id'), 'reposts', ['tweet_id'], unique=False)
    op.create_index(op.f('ix_reposts_user_id'), 'reposts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reposts_user_id'), table_name='reposts')
    op.drop_index(op.f('ix_reposts_tweet_id'), table_name='reposts')
    op.drop_index(op.f('ix_reposts_id'), table_name='reposts')
    op.drop_table('reposts')
    # ### end Alembic commands ###
